Fix some flake8 coding style issues
packagecontrol/package_reviewer pull request #10
Opened 2017-06-01 15:29 UTC by gerardroche

This adds ignore rules for several specific docstring warnings in the
form of D*.  Those warnings tend to create a lot of flake8 noise.

Several other warnings have been fixed.

2017-06-01 21:37 UTC, FichteFoll requested changes
I'm generally not against linting for docstrings, but that only makes sense if you actually took the effort to write some. I didn't, or only for a select few functions, which is why don't consider docstring linting worth it for this project. 

As such, I'm going to reject this pull request. I'll apply a few of your whitespace changes manually, though. Thanks for your efforts regardless.

2017-06-01 21:37 UTC, FichteFoll commented on st_package_reviewer/__main__.py
> +    """Main.
This docstring is later used to generate the help message, which is sub-optimal but works. Your change introduced a random "Main." in the help message.

2017-06-01 21:37 UTC, FichteFoll commented on tests/test_file_checkers.py
> +        failure_asserts or
I prefer having the binary operator on the new line to more clearly show its relation to the above line. I believe there is an error code for this that goes both ways, so I'll see if I can enable this check for the future.

2017-06-01 21:37 UTC, FichteFoll commented on tox.ini
> +ignore = D100, D101, D102, D103, D104, D105
Flake8, by default, doesn't check docstrings. You must have a flake8 plugin installed in your system/environment.

Also refer to the list of default errors: http://flake8.pycqa.org/en/latest/user/error-codes.html

2017-06-01 21:37 UTC, closed without merging

2017-06-01 22:12 UTC, FichteFoll commented
After experimenting with flake8-docstrings for a bit, this didn't turn out to be that bad of an idea, so I added it in c96f1f2b3bf90799324d7095c6cb74fc3b3511d0.

Also quite unfortunately the error code for not having a line break before binary operators rather then after is still WIP: https://github.com/PyCQA/pycodestyle/pull/502.

2017-06-02 20:39 UTC, gerardroche commented
Adding the ignore rules for the docstrings doesn't hurt, in fact it tends to hurt not to, unless I'm doing something wrong. 

I use SublimeLinter and it automatically shows lots of docstring errors without those ignore rules. I'm sure there's a way to disable the docstring checks per project or enable them per project but I find it easier to add the ignore rules and fix the issues. Code usually conforms for the most part, at least without those few high noise rules.